### ISSUE TITLE
django-cloudinary-storage does not anticipate Windows paths

### ISSUE THREAD

**Issue by tundebabzy** [klis87/django-cloudinary-storage#1]
If a document is named using Windows styled path, the `_save` method causes problems.

    def _save(self, name, content):
        # name is path\to\some\image\image.jpg on Windows machine
        name = self._prepend_prefix(name)
        # name becomes media/path\to\some\image\image.jpg if `settings.MEDIA_URL` is /media/
        ...

At the end, the resulting filename on cloudinary is something like media/\path\to\some\image\image_asdfghjk.jpg/ causing cloudinary to complain.

I think it will be nice if `django-cloudinary-storage` also works well on Windows. I can supply a fix which makes sure the `name` variable in `_save` is in unix style.

**Comment by klis87** [comment]
I will check it on my windows system soon, it should work right now as I intended this package to work on Windows as well, thanks for letting me know, I will try to fix this in the following days.

**Comment by klis87** [comment]
By the way, I would like to make sure, by path\to\some\image\image.jpg you mean that this is not actual path to image.jpg, but  it is the file name, right?

**Comment by tundebabzy** [comment]
Yes. This is just the file name.

**Comment by klis87** [comment]
Thank you for your commits' references.

I am just wondering about one thing, which I am missing. Why a file with a filename like path\to\some\image\image.jpg is created in the first place? Could you please provide me a sample of your Django model/view code, when this situation could arise, so I could understand this issue better? Unless path\to\some\image\image.jpg is just the hardcoded file name?

**Comment by tundebabzy** [comment]
I'm using django-zinnia for the project. With all default settings, uploading a picture from the zinnia app fails when I'm working on a windows machine. After investigating, I discovered that the name of the image django-cloudinary-storage was receiving is in the 'file path form'. I'm presently on ubuntu but I'll reproduce the issue on my windows machine shortly and show the full stack trace

**Comment by tundebabzy** [comment]
Here are snapshots of the error.

![t](https://cloud.githubusercontent.com/assets/818803/21865358/05d233ca-d846-11e6-8c2d-4e73922d08de.JPG)
![t2](https://cloud.githubusercontent.com/assets/818803/21865364/0b3885da-d846-11e6-9343-9a3cb7c380af.JPG)
![t3](https://cloud.githubusercontent.com/assets/818803/21865373/10fe153e-d846-11e6-9eda-6808569da1c9.JPG)

By default, zinnia uploads to a directory named 'uploads' concatenated with the year, month and day the image was saved hence in this particular case - 'uploads\zinnia\2017\01\11\'.

Let me know if you need any more information.

**Comment by klis87** [comment]
Thank you for the explanation, now everything is clear, I will test it myself in the evening on WIndows machine, accept merge request and upload new version to pypi.

**Comment by tundebabzy** [comment]
That will be nice. Thanks.

**Comment by klis87** [comment]
Thank you for your pull request. I added 1 comment to it, please review it, thanks in advance.
