### ISSUE TITLE
Setting for prefix

### ISSUE THREAD

**Issue by seroy** [klis87/django-cloudinary-storage#11]
Currently prefix is based on MEDIA_URL setting. It would be nice to have abbility to customize prefix via CLOUDINARY_STORAGE. I can make PR for this, if it's necessary.

**Comment by klis87** [comment]
Why do you need this? Cloudinary storage is just a custom Django storage implementation, which can be used for both static and media files. The default Django storages use MEDIA_URL and STATIC_URL settings, and in my opinion there is no need to introduce dedicated prefix settings for CLOUDINARY_STORAGE, as it would cause a following problems:
- unnecessary API pollution
- making CLOUDINARY_STORAGE less portable - the less work needs to be done when changing storages, the better

**Comment by seroy** [comment]
I have 
```
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
MEDIA_URL = '/uploaded/'
```
 but for some models/fields used `cloudinary_storage.storage.MediaCloudinaryStorage` and ran into side effect that all files uploaded at cloudinary via cloudinary_storage prefixed by '/uploaded/'

Code change is minimal, simple and 100% reverse compatible. In  [app_settings.py ](https://github.com/klis87/django-cloudinary-storage/blob/master/cloudinary_storage/app_settings.py) add new line:
```
PREFIX = user_settings.get('PREFIX', settings.MEDIA_URL)
```

In [storage.py](https://github.com/klis87/django-cloudinary-storage/blob/master/cloudinary_storage/storage.py#L112) change `_get_prefix` method to:
```
def _get_prefix(self):
   return app_settings.PREFIX
```

May be for most cloudinary-storage users it is not principal and they will never change that setting, but it make sense in my case.

**Comment by klis87** [comment]
I see your use case now, and, as this will be backward compatible, we can include this in the package.

As I am quite busy recently, so I would really appreciate PR. Please include a test for this case.
