### ISSUE TITLE
How to get the full path

### ISSUE THREAD

**Issue by sgaseretto** [klis87/django-cloudinary-storage#15]
This package is awesome, but I have one question, when I query something that has an ImageField, how do I get the full path? Now I get only something like ```media/images/uploaded_image.png``` 

NOTE: I'm using graphql to query this, so I don't know if there if the rest of the path is completed by the cloudinary tag in the template or something like that

**Comment by klis87** [comment]
If you have a `Model` with `image` field, you should be able to get full url with `model_instance.image.url`, in any place desired (a graphql resolver too).

**Comment by sgaseretto** [comment]
The thing is I'm doing a query that brings many items with my resolver, something like:
```
def resolve_items(self, info):
    return Item.objects.all()
```
Where the Item model is something like:
```
class Item(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
```
And I want to get the urls and all the additional, any Idea of how to specify that in the query or something like that?

**Comment by klis87** [comment]
maybe try 
`
query {
  items {
    image {
      url
    }
  }
}
`

But I dont know whether it would work out of the box, I didnt use Graphene and generally graphql with Python, so it is possible that you will need to write your custom resolvers to provide urls.

But this package should give you anything you need to achieve it, if you have problems, maybe ask on graphene issues, but I hope my snippet will help you. Good luck!

**Comment by sgaseretto** [comment]
It seems that at the moment graphene only supports that type of queries for FileField, not for ImageField yet. But thanks a lot for your help!

**Comment by klis87** [comment]
You could always write your own resolver I guess for now, I guess I can close this :)
