### ISSUE TITLE
How can I delete an image each time I delete the instance asociated with it?

### ISSUE THREAD

**Issue by sgaseretto** [klis87/django-cloudinary-storage#16]
If I have a model that has an ImageField as an attribute, how can I delete the image each time I do model_instance.delete()? I've seen that there is the ```deleteorphanedmedia``` command, but I don't understand how to use it each time I delete something that has an image.
What extra steps do I need to add to achieve this so I stop having orphan images?

**Comment by klis87** [comment]
This is just how Django works for media files, it works the same for all storages, this is by design. If you dont like it, you can use Django signals or you can delete given file in overwritten delete model method, pls see Django docs for more info

**Comment by sgaseretto** [comment]
I understand. Is there a way to at least get the public_id from the image and delete it doing something like
``` cloudinary.uploader.destroy(custommodel.image.public_id,invalidate=True) ```

**Comment by klis87** [comment]
Field file actually has `delete` method, so you should be able to do this: `model_instance.file_field.delete()` before deleting the whole model instance. (https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.fields.files.FieldFile.delete) Also, you should be able to do this: `storageInstance.delete(model_instance.file_field.name)`.

You should never do sth like `cloudinary.uploader.destroy(custommodel.image.public_id,invalidate=True)`, thats why you use storage from this package which does those low level things for you :). See https://github.com/klis87/django-cloudinary-storage/blob/master/cloudinary_storage/storage.py#L73

**Comment by sgaseretto** [comment]
That is what I was looking for!
I did the following
```
    storage_instace.delete(name=custommodel.file.name)
    custommodel.delete()
```
 and it works great. Thanks a lot
