### ISSUE TITLE
Django-utils.six dropped in Django 3.x

### ISSUE THREAD

**Issue by nsjcorps** [klis87/django-cloudinary-storage#18]
Django 3.x has dropped django.utils.six. It is just six now https://pypi.org/project/six/.

So you might want to consider adding that to a new version.

The package is quite helpful though

**Comment by tiagocordeiro** [comment]
The package is very useful for me too.

**Comment by klis87** [comment]
Glad u find it useful. However, I dont use Django at the moment at all, so I cannot spend time developing for now. I will happily accept pull requests though.

**Comment by tomek-i** [comment]
as the PR hasnt been merged yet and I am playing around with this service and heroku and django 3, is there a way for me to get it going without waiting for the merger?

**Comment by nsjcorps** [comment]
No. You have to downscale to django 2.x

**Comment by klis87** [comment]
@tomek-i  @nsjcorps do you know why it does not work for django 3? it is about this compat six package or something else too? PR https://github.com/klis87/django-cloudinary-storage/pull/19 I guess most of the job has already done, but there are some commented tests failing and I want it to be solved first before merging

**Comment by tiagocordeiro** [comment]
@tomek-i  i'm testing in some personal projects, with heroku and django3, you can use it even before the merger, you can reference in your requirements.txt something like `git+git://github.com/tiagocordeiro/django-cloudinary-storage@Django3Support`, you can see an example here: https://github.com/tiagocordeiro/djmenu/blob/master/requirements.txt#L33, But, please understand, there may still be some instability.

@ klis87 I still haven't got time to dedicate myself to PR, I'll try again this weekend. I need to study a little more about the mock. I apologize for that.

**Comment by klis87** [comment]
@tiagocordeiro no worries for that, please do not apologize, I really appreciate your work, just wanted to know whether it is ok to be reviewed and merged or not yet.

**Comment by qkral** [comment]
I'd be supper happy to have the django-3 compatible version as well. As far as I see it just comes down replacing 3 django.utils.six to six

**Comment by klis87** [comment]
Hopefully issue solved by 0.3.0 release
