### ISSUE TITLE
Unable to load large videos

### ISSUE THREAD

**Issue by nsjcorps** [klis87/django-cloudinary-storage#20]
I tried to upload a video of about 20MB. It just keeps loading. Nothing happens!

The browser just keeps loading.

**Comment by klis87** [comment]
Do you have any errors? It could be Django limit exceeded, your proxy server, maybe even pycloudinary has some limit or cloudinary itself.

**Comment by nsjcorps** [comment]
@klis87 I have resolved it. The issue was my network sup it kept timing out. It's all good now. Thanks for your response. 

Cloudinarys upload limit is 100mb for the free plan

**Comment by klis87** [comment]
@nsjcorps ok, good to hear, thx for the response.
