### ISSUE TITLE
Issue with uploading Django CKEditor images to cloudinary

### ISSUE THREAD

**Issue by ashutoshkrris** [klis87/django-cloudinary-storage#28]
Everything is working fine if I don't use Cloudinary. But when I am using Cloudinary for storing media files, it is throwing error:
```
Internal Server Error: /ckeditor/upload/
Traceback (most recent call last):
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\ckeditor_uploader\views.py", line 118, in post
    saved_path = filewrapper.save_as(filepath)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\ckeditor_uploader\backends\pillow_backend.py", line 54, in save_as
    saved_path = self.storage_engine.save(filepath, self.file_object)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\django\core\files\storage.py", line 52, in save
    return self._save(name, content)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\cloudinary_storage\storage.py", line 68, in _save
    response = self._upload(name, content)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\cloudinary_storage\storage.py", line 62, in _upload
    return cloudinary.uploader.upload(content, **options)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\cloudinary\uploader.py", line 46, in upload
    return call_cacheable_api("upload", params, file=file, **options)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\cloudinary\uploader.py", line 341, in call_cacheable_api
    result = call_api(action, params, http_headers, return_error, unsigned, file, timeout, **options)
  File "C:\Users\ashut\.virtualenvs\Blog-OHIX9BKG\lib\site-packages\cloudinary\uploader.py", line 428, in call_api
    raise Error(result["error"]["message"])
cloudinary.exceptions.Error: Invalid image file
```

My urls patterns : 
```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/',include('authentication.urls')),
    path('',include('core.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

My media files storage settings : 
```
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config("CLOUD_NAME"),
    'API_KEY': config("API_KEY"),
    'API_SECRET': config("API_SECRET")
}


# Media Files
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# CKEditor Configurations
CKEDITOR_UPLOAD_PATH = "blog/uploads/"
```

**Comment by klis87** [comment]
Are you sure everything is configured correctly? You could try to lunch example app https://github.com/klis87/django-cloudinary-storage/tree/master/tests as a start

**Comment by ashutoshkrris** [comment]
> Are you sure everything is configured correctly? You could try to use an example app https://github.com/klis87/django-cloudinary-storage/tree/master/tests as a start point

Yes, everything is working fine for files that are being uploaded normally (i.e. not by ckeditor).
The error is thrown when user tries to upload files using ckeditor

**Comment by klis87** [comment]
@ashutoshkrris this means that there must be sth wrong with integration of ckeditor and upload fields

maybe it doesn't work anymore at this time with the newest versions, but I remember I used both of those libraries in the past with success. Maybe below snippets would help you:
```python
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.core.exceptions import ValidationError

from ckeditor_uploader.fields import RichTextUploadingField

class Post(models.Model):
    title = models.CharField(max_length=60, unique=True)
    slug = models.SlugField(max_length=60, unique=True, editable=False)
    description = models.TextField(max_length=155)
    content = RichTextUploadingField()
    previous_post = models.OneToOneField('self', null=True, blank=True, related_name='next_post',
                                         on_delete=models.PROTECT)
    published = models.BooleanField(default=False)
    publication_date = models.DateTimeField(default=timezone.now)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def clean(self):
        if self.previous_post_id is not None and self.id == self.previous_post_id:
            raise ValidationError('Previous post cannot be the same as post itself.')

    def has_next(self):
        try:
            self.next_post
        except Post.DoesNotExist:
            return False
        else:
            return self.next_post.published

    def has_previous(self):
        return self.previous_post is not None and self.previous_post.published
```
and part of settings.py
```python
INSTALLED_APPS = [
    'blog.apps.BlogConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'captcha',
    'cloudinary',
    'cloudinary_storage',
    'jdg',
    'material',
    'parsley',
    'ckeditor',
    'ckeditor_uploader',
    'authorization',
]

```python
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    'EXCLUDE_DELETE_ORPHANED_MEDIA_PATHS': ('posts/',)
}

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CKEDITOR_UPLOAD_PATH = 'media/posts/'
CKEDITOR_BROWSE_SHOW_DIRS = False

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'width': 1000,
        'height': 500,
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Source', '-', 'Preview'],
            ['Undo', 'Redo'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
             'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'HorizontalRule', 'Iframe', 'PageBreak', 'SpecialChar'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks'],
            ['CodeSnippet']
        ],
        'extraPlugins': 'codesnippet',
        'codeSnippet_languages': {
            'xml': 'XML',
            'bash': 'Bash',
            'css': 'CSS',
            'markdown': 'Markdown',
            'django': 'Django',
            'dockerfile': 'Dockerfile',
            'handlebars': 'Handlebars',
            'http': 'HTTP',
            'javascript': 'JavaScript',
            'json': 'JSON',
            'nginx': 'Nginx',
            'python': 'Python',
            'scss': 'SCSS',
            'sql': 'SQL'
        },
    },
}
```

**Comment by ashutoshkrris** [comment]
> @ashutoshkrris this means that there must be sth wrong with integration of ckeditor and upload fields
> 
> maybe it doesn't work anymore at this time with the newest versions, but I remember I used both of those libraries in the past with success. Maybe below snippets would help you:
> 
> ```python
> from django.db import models
> from django.core.urlresolvers import reverse
> from django.utils import timezone
> from django.utils.text import slugify
> from django.core.exceptions import ValidationError
> 
> from ckeditor_uploader.fields import RichTextUploadingField
> 
> class Post(models.Model):
>     title = models.CharField(max_length=60, unique=True)
>     slug = models.SlugField(max_length=60, unique=True, editable=False)
>     description = models.TextField(max_length=155)
>     content = RichTextUploadingField()
>     previous_post = models.OneToOneField('self', null=True, blank=True, related_name='next_post',
>                                          on_delete=models.PROTECT)
>     published = models.BooleanField(default=False)
>     publication_date = models.DateTimeField(default=timezone.now)
>     tag = models.ManyToManyField(Tag)
> 
>     def __str__(self):
>         return self.title
> 
>     def get_absolute_url(self):
>         return reverse('post', kwargs={'slug': self.slug})
> 
>     def save(self, *args, **kwargs):
>         self.slug = slugify(self.title)
>         super().save(*args, **kwargs)
> 
>     def clean(self):
>         if self.previous_post_id is not None and self.id == self.previous_post_id:
>             raise ValidationError('Previous post cannot be the same as post itself.')
> 
>     def has_next(self):
>         try:
>             self.next_post
>         except Post.DoesNotExist:
>             return False
>         else:
>             return self.next_post.published
> 
>     def has_previous(self):
>         return self.previous_post is not None and self.previous_post.published
> ```
> 
> and part of settings.py
> 
> ```python
> INSTALLED_APPS = [
>     'blog.apps.BlogConfig',
>     'django.contrib.admin',
>     'django.contrib.auth',
>     'django.contrib.contenttypes',
>     'django.contrib.sessions',
>     'django.contrib.messages',
>     'django.contrib.staticfiles',
>     'django.contrib.sitemaps',
>     'captcha',
>     'cloudinary',
>     'cloudinary_storage',
>     'jdg',
>     'material',
>     'parsley',
>     'ckeditor',
>     'ckeditor_uploader',
>     'authorization',
> ]
> 
> ```python
> CLOUDINARY_STORAGE = {
>     'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
>     'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
>     'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
>     'EXCLUDE_DELETE_ORPHANED_MEDIA_PATHS': ('posts/',)
> }
> 
> STATIC_URL = '/static/'
> STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
> STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
> 
> MEDIA_URL = '/media/'
> DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
> 
> CKEDITOR_UPLOAD_PATH = 'media/posts/'
> CKEDITOR_BROWSE_SHOW_DIRS = False
> 
> CKEDITOR_CONFIGS = {
>     'default': {
>         'skin': 'moono',
>         'width': 1000,
>         'height': 500,
>         'toolbar': 'Custom',
>         'toolbar_Custom': [
>             ['Source', '-', 'Preview'],
>             ['Undo', 'Redo'],
>             ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
>             ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
>              'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
>             ['Link', 'Unlink', 'Anchor'],
>             ['Image', 'HorizontalRule', 'Iframe', 'PageBreak', 'SpecialChar'],
>             ['Styles', 'Format', 'Font', 'FontSize'],
>             ['TextColor', 'BGColor'],
>             ['Maximize', 'ShowBlocks'],
>             ['CodeSnippet']
>         ],
>         'extraPlugins': 'codesnippet',
>         'codeSnippet_languages': {
>             'xml': 'XML',
>             'bash': 'Bash',
>             'css': 'CSS',
>             'markdown': 'Markdown',
>             'django': 'Django',
>             'dockerfile': 'Dockerfile',
>             'handlebars': 'Handlebars',
>             'http': 'HTTP',
>             'javascript': 'JavaScript',
>             'json': 'JSON',
>             'nginx': 'Nginx',
>             'python': 'Python',
>             'scss': 'SCSS',
>             'sql': 'SQL'
>         },
>     },
> }
> ```

Could you remember the specific versions of django-ckeditor and django-cloudinary-storage used? Or else you can send me repository link that contains this code (if it exists)

**Comment by klis87** [comment]
```
cloudinary==1.7.0
Django==1.11
django-ckeditor==5.2.2
django-cloudinary-storage==0.2.1
django-debug-toolbar==1.7
django-material==0.13.1
django-parsley==0.6
django-pure-pagination==0.3.0
django-recaptcha==1.3.0
gunicorn==19.7.1
Pillow==4.0.0
psycopg2==2.7.1
pytz==2016.4
whitenoise==3.3.0
eventlet==0.20.1
gevent==1.2.1
```

**Comment by ashutoshkrris** [comment]
I found the solution.
The main problem was, I was using Pillow as the Image backend.
I removed it and it was resolved. Thanks for the help!

**Comment by klis87** [comment]
@ashutoshkrris cool, good news!
