### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by aaqidmasoodi** [klis87/django-cloudinary-storage#36]
I am trying to push my static files to Cloudinary but I am getting an error :
expected str, bytes or os.PathLike object, not NoneType

I am using Django 4.1.
[django_errors.log](https://github.com/klis87/django-cloudinary-storage/files/12524481/django_errors.log)

I jave attached my log file. I am not able to figure out why this is happening. please help

**Comment by nathius262** [comment]
intead of using this in your django application;
`STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'`

change it to this
`STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticCloudinaryStorage'`

that will solve the problem.
