### ISSUE TITLE
All static gets uploaded as "raw"

### ISSUE THREAD

**Issue by si14** [klis87/django-cloudinary-storage#7]
The title says it all.

One of the reasons why that's less than ideal is limits, e.g. Cloudinary's size limit for "raw" files is lower than for videos.

If I understand correctly, it's not an intended behavior.

I'm using the "default" setup (as shown on README.md), here is a piece of debug log during `collectstatic`:

```
Copying '/blahblah/build/media/instructions.jpg'
DEBUG 2017-06-16 17:19:08,706 connectionpool.py:_new_conn:818 Starting new HTTPS connection (1): res.cloudinary.com
DEBUG 2017-06-16 17:19:08,857 connectionpool.py:_make_request:395 https://res.cloudinary.com:443 "HEAD /blahblah/raw/upload/v1/static/media/instructions.jpg HTTP/1.1" 404 0
/Users/si14/.virtualenvs/melsciwebpy3/lib/python3.5/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG 2017-06-16 17:19:09,193 connectionpool.py:_make_request:395 https://api.cloudinary.com:443 "POST /v1_1/blahblah/raw/upload HTTP/1.1" 200 504
```

As you can see, stuff gets uploaded to `/raw/`.

**Comment by klis87** [comment]
Good points :) This is exactly why I added ```STATIC_IMAGES_EXTENSIONS``` setting some time ago, please check it in readme and let me know whether it helps you.

**Comment by klis87** [comment]
I am closing this, please comment on this issue if my solution didn't help you out.
